In [1]:
import pandas as pd

In [ ]:
df_100 = pd.read_csv("../../results/tables/source/fs_w2v_2_top100.tsv", sep="\t")
df_100.head()

,Id,Chi-2,Feature,LightGBM,Logistics,Pearson,RFE,Random Forest,Total
0,1,True,шанс,True,True,True,True,True,6
1,2,True,чувств,True,True,True,True,True,6
2,3,True,фокусира,True,True,True,True,True,6
3,4,True,фенов,True,True,True,True,True,6
4,5,True,факта,True,True,True,True,True,6

In [ ]:
df_104 = pd.read_csv("../../results/tables/source/fs_w2v_2_top104.tsv", sep="\t")
df_104.head()

,Id,Feature,Pearson,Chi-2,RFE,Logistics,Random Forest,LightGBM,Total
0,1,шанс,True,True,True,True,True,True,6
1,2,чувств,True,True,True,True,True,True,6
2,3,фокусира,True,True,True,True,True,True,6
3,4,фенов,True,True,True,True,True,True,6
4,5,факта,True,True,True,True,True,True,6

In [5]:
df_100f = df_104.head(100)
df_100f.shape

(100, 9)

In [6]:
for col in df_100.columns:
    comparison = df_100[col] == df_100f[col]
    mismatches = (~comparison).sum()
    print(f"Column '{col}': {mismatches} mismatches")

Column 'Id': 0 mismatches
Column 'Chi-2': 0 mismatches
Column 'Feature': 0 mismatches
Column 'LightGBM': 0 mismatches
Column 'Logistics': 0 mismatches
Column 'Pearson': 0 mismatches
Column 'RFE': 0 mismatches
Column 'Random Forest': 0 mismatches
Column 'Total': 0 mismatches

In [ ]:
df_104.to_latex("../../results/tables/latex/fs_w2v_2.tex", index=False, longtable=True)